### PR TITLE
Add ~arm keyword to all ebuilds to support 32bit ARM SBCs

### PR DESCRIPTION
**Pull request by ivecera**
Hi Andreas,
here is the promised PR with ~arm enablement. I'm currently using your repo to run Home Assistant on my Odroid XU4.

Changes were generated via:

`/usr/local/portage/homeassistant # find . -name *.ebuild | xargs ekeyword ~arm`
`/usr/local/portage/homeassistant # repoman -v -j4 manifest`

### CODE REVIEW

**Comment by onkelbeh** [comment]
Could you please pull & push again, so I can merge it, I saw it after the 0.117.6 updates.

**Comment by onkelbeh** [comment]
Could you please pull & push again, so I can merge it, I saw it after the 0.117.6 updates.

**Comment by ivecera** [comment]
> Could you please pull & push again, so I can merge it, I saw it after the 0.117.6 updates.

Done

**Review by onkelbeh — COMMENTED** [review]
Ok, lets give it a try.

**Comment by ivecera** [comment]
Everything looks good on my xu4...

**Comment by onkelbeh** [comment]
Still have some smaller updates on new Ebuilds to do, then I'll push it to the Gentoo mirrors.

**Comment by onkelbeh** [comment]
Did not know the -j at repoman, still learning :-)

**Comment by onkelbeh** [comment]
It was added as beta even in stable Ebuild, I think we can leave it like that.
My build scripts will add it as stable in future when the other Keywords are stable.

**Pull request merged**
