### PR TITLE
fix missing useflags in IUSE in homeassistant-full

### PR DESCRIPTION
**Pull request by ivecera**
Several ebuilds for homeassistant-full are missing corresponding entries in IUSE for the following use flags:

bom (0.117.0_beta6 & 0.117.0)
frontend (0.115*, 0.116*, 0.117*, 9999)
hyperion (0.116*,  0.117.0_beta6 & 0.117.0)
isy994 (0.117.0_beta6 & 0.117.0)
splunk (0.116*, 0.117.0_beta6 & 0.117.0)
tensorflow (0.117.0_beta6 & 0.117.0)

### CODE REVIEW

**Comment by onkelbeh** [comment]
Ok, could be, I do currently no bigger tests the -full Ebuild, and will take a closer look end of the week.
These Ebuild are automatically deployed with an experimental script, perhaps some checks are not working properly.
Already have some ideas, tensorflow 2.3.0 was not yet available at build time of the older 0.117 Ebuilds,
frontend is obsolete, have to check the others.

Thanks for reporting.

**Comment by onkelbeh** [comment]
One question in general: do you build on RPi?

**Comment by ivecera** [comment]
No, I'm using Odroid-XU4 ... I would like to submit a follow-up (next PR) to add ~arm keyword.

**Comment by onkelbeh** [comment]
Hi,
had to fix it manually, somehow the build script did not parse missing deps correctly.
I did not change the ebuild releases for better comparability, these all are outdated or dev, so this won't hurt a lot.

bom (0.117.0) 
frontend (0.115*, 0.116*, 0.117*, 9999) (removed the unnecessary USE dep)
hyperion (0.116*,  0.117.0)
isy994 (0.117.0)
splunk (0.116*,  0.117.0)
tensorflow (0.117.0)

the mentioned beta build died already.

Please let me know where exactly you want the arm keyword added, I have some build scripts, perhaps we can save some work here. At least the main ebuilds are generated, most of the dev-python Ebuilds are updated manually, although the initial import is automated.
comitted in https://github.com/onkelbeh/HomeAssistantRepository/commit/f69ae5a83b17077eb83da3ed79b9c30c6fe73630

**Comment by ivecera** [comment]
> ...
> 
> Please let me know where exactly you want the arm keyword added, I have some build scripts, perhaps we can save some work here. At least the main ebuilds are generated, most of the dev-python Ebuilds are updated manually, although the initial import is automated.

I'm going to create another PR with ~arm enablement... It will add ~arm keyword to all ebuilds where is it missing.

**Pull request closed without merging**
