### PR TITLE
Add missing mobile_app dependency python-jose

### PR DESCRIPTION
**Pull request by klowe0100**

### CODE REVIEW

**Comment by inode64** [comment]
The real problem is  that pycognito needs python-jose to run.
I make the correct fix #35

**Comment by onkelbeh** [comment]
Fixed by https://github.com/onkelbeh/HomeAssistantRepository/commit/7f670cc2374e85fca4d2562d7b6364fa9b0d83e1, so this one can be closed.

**Comment by alfredfo** [comment]
https://github.com/onkelbeh/HomeAssistantRepository/blob/master/dev-python/pycognito/pycognito-2024.2.0.ebuild <- removed again and I see the same issue.

Manually emerging python-jose fixes it.

**Comment by alfredfo** [comment]
@onkelbeh

**Pull request closed without merging**
