### PR TITLE
WIP: Esphome python3

### PR DESCRIPTION
**Pull request by klowe0100**
Hi! Great job on this overlay. I think we have a similar philosophy for our desired configurations. I was working on getting things installed today while avoiding any python2. I wasn't super meticulous about regression testing all versions, but I'm up and running. (platformio 4.0.0 is probably good enough) I'll probably start experimenting a pure python3.7 install soon too. Just send notes if you'd like me to go back and make changes. Hope this saves you some typing and thanks for your efforts on this. Cheers.

### CODE REVIEW

**Comment by klowe0100** [comment]
Oops. Sorry ignore this for now. Still a few dependencies to work through

**Comment by onkelbeh** [comment]
Thanks for your help, @klowe0100. Had some problems to get esphome running, so i just went to platformio-4.0.3. Currently i have no machine without python-2.7, so i cannot issue a clean test, but the current esphome-dev with pio-4.0.3 compiles all my files without problems, i just cannot tell if it runs with python-3.6 or with 2.7

**Comment by onkelbeh** [comment]
Not sure, but the process tree indicates it really runs on python-3.6.
I'm afraid we have to patch in esphome, looks like it's requirements parser checks for a platformio installation in the python-2.7 directories. Will ask @OttoWinter for help as soon i have some time.

**Comment by onkelbeh** [comment]
Just FYI:
```
root@g18-hass:/etc/esphome # eix -I esphome
[?] dev-embedded/esphome [1]
     Verfügbare Versionen:   ~1.11.1-r1 ~1.11.2-r1 ~1.12.0_beta3 ~1.12.0_beta4 1.12.0 1.12.0-r1 1.13.2 1.13.6 ~1.13.6-r1 ~9999*l {server test PYTHON_TARGETS="python2_7 python3_6 python3_7"}
     Installierte Versionen: 9999*l(20:13:50 30.09.2019)(server -test PYTHON_TARGETS="python3_6 -python3_7")
     Startseite:             https://github.com/esphome/esphome https://pypi.org/project/esphome/
     Beschreibung:           Make creating custom firmwares for ESP32/ESP8266 super easy.

[I] dev-python/aioesphomeapi [1]
     Verfügbare Versionen:   ~1.7.0 ~2.0.0 ~2.0.1 ~2.1.0 (~)2.2.0 {test PYTHON_TARGETS="python3_5 python3_6 python3_7"}
     Installierte Versionen: 2.2.0(09:51:45 03.08.2019)(-test PYTHON_TARGETS="python3_6 -python3_5 -python3_7")
     Startseite:             https://esphome.io/ https://pypi.org/project/aioesphomeapi/

[1] "HomeAssistantRepository" /usr/portage/homeassistant

2 Treffer
root@g18-hass:/etc/esphome # eix -I platformio
[I] dev-embedded/platformio
     Verfügbare Versionen:   ~3.6.1-r1[1] ~3.6.3[1] ~3.6.4[1] ~3.6.5[1] ~3.6.7[1] (~)4.0.0[1] (~)4.0.1 (~)4.0.3[1] {PYTHON_SINGLE_TARGET="python2_7 python3_5 python3_6 python3_7" PYTHON_TARGETS="python2_7 python3_5 python3_6 python3_7"}
     Installierte Versionen: 4.0.3[1](20:54:15 30.09.2019)(PYTHON_SINGLE_TARGET="python3_6 -python2_7 -python3_7" PYTHON_TARGETS="python2_7 python3_6 -python3_7")
     Startseite:             https://platformio.org/
     Beschreibung:           An open source ecosystem for IoT development

[1] "HomeAssistantRepository" /usr/portage/homeassistant
root@g18-hass:/etc/esphome #
```

**Pull request merged**
