### PR TITLE
Include retry to 20 seconds to fix daemon shutdown and start after daemons that can be used

### PR DESCRIPTION
**Pull request by inode64**
Include retry to 20 seconds to fix daemon shutdown, this close https://git.edevau.net/onkelbeh/HomeAssistantRepository/issues/260
Start hass after starting daemons that can be used

### CODE REVIEW

**Comment by inode64** [comment]
I have tried to access https://git.edevau.net/ and it denies me access, it does not send emails to create the password again :-(

**Comment by onkelbeh** [comment]
Many Thanks.
You can submit at both sites,
I hope I just fixed the Email issue at git.edevau.net, caused by a postfix update.

**Comment by onkelbeh** [comment]
shouldn't the RETRY parameter be passed to start_stop_daemon?

```
start_stop_daemon_args="--user $user --stdout $stdoutlog --stderr $serverlog --wait 10 -R $retry"
```

The `start-stop-daemon: 1 process refused to stop` only occures at my production box if HA ist running > 5-6 hours, so it takes some time to test.

**Comment by onkelbeh** [comment]
Looks like start() does not eat what stop() needs:
` * using --retry with --start has no effect, use --wait instead`

**Comment by inode64** [comment]
"retry" is an internal variable of openrc, You see **man openrc-run** for more info.
see other usage examples: /etc/init.d/dnsmasq , /etc/init.d/unifi, /etc/init.d/influxdb

**Comment by inode64** [comment]
Is there a problem or something is missing to be able to add this pull?

**Pull request merged**
